[build]
    functions="functions"
    publish = "public"

[[redirects]]
    from="/api/*"
    to="/.netlify/functions/:splat"
    status=200
[[redirects]]
    from="/5e9t1"
    to="https://youtu.be/-gSqdlnEkGA"
    status=200