[build]
    functions="functions"
    public="public"

[[redirects]]
    from="/api/*"
    to="/.netlify/functions/:splat"
    status=200
    
[[redirects]]
    from="/p/*"
    to="/public/:splat"
    status=200
    
[[redirects]]
    from="/*"
    to="/.netlify/functions/redirect/:splat"
    status=200