[build]
    functions="functions"
    publish = "public"

[[redirects]]
    from="/api/*"
    to="/.netlify/functions/:splat"
    status=200
    
[[redirects]]
    from="/sign-in"
    to="/sign-in"
    status=200
    
[[redirects]]
    from="/*"
    to="/redirect.html"
    status=200